<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales Report – {{ $rangeLabel }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }

        /* DejaVu Sans ships with DomPDF and includes the peso sign (₱) */
        body {
            font-family: "DejaVu Sans", sans-serif;
            font-size: 10px;
            color: #000;
            background: #fff;
            padding: 32px 36px;
        }

        /* ── Header (table layout: DomPDF does not support flexbox) ── */
        .header {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
        }
        .header td      { vertical-align: top; padding-bottom: 14px; }
        .header .right  { text-align: right; }
        .brand      { font-size: 19px; font-weight: bold; color: #000; }
        .brand-sub  { font-size: 9px; color: #555; margin-top: 3px; }
        .rpt-title  { font-size: 15px; font-weight: bold; color: #000; }
        .rpt-meta   { font-size: 9px; color: #555; margin-top: 3px; }

        /* ── KPI Cards (3 across) ── */
        .kpi-row    { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        .kpi-card   {
            width: 33%;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 14px 16px;
            vertical-align: top;
        }
        .kpi-gap    { width: 14px; }
        .kpi-label  { font-size: 8px; font-weight: bold; color: #555; text-transform: uppercase; letter-spacing: .06em; margin-bottom: 6px; }
        .kpi-value  { font-size: 19px; font-weight: bold; color: #000; }

        /* DejaVu Sans gives the peso glyph a wide advance; pull digits tight to it */
        .peso       { letter-spacing: -0.15em; }

        /* ── Table ── */
        table.data  { width: 100%; border-collapse: collapse; }
        table.data thead th {
            padding: 8px 10px;
            text-align: left;
            font-size: 8px;
            font-weight: bold;
            color: #555;
            text-transform: uppercase;
            letter-spacing: .06em;
            border-top: 2px solid #000;
            border-bottom: 1px solid #ccc;
        }
        table.data tbody td {
            padding: 9px 10px;
            font-size: 10px;
            color: #000;
            border-bottom: 1px solid #e8e8e8;
        }
        .tx-id      { font-weight: bold; color: #000; }
        .th-amt,
        .td-amt     { text-align: left; }
        .td-amt     { font-weight: bold; }

        /* Method pill */
        .method-pill {
            display: inline-block;
            background: #f0f0f0;
            color: #000;
            font-size: 9px;
            font-weight: bold;
            padding: 2px 10px;
            border-radius: 20px;
        }

        /* Total row */
        .total-row td {
            border-top: 2px solid #000;
            border-bottom: none;
            font-weight: bold;
            font-size: 11px;
            padding-top: 10px;
        }

        /* ── Footer ── */
        .footer {
            width: 100%;
            border-collapse: collapse;
            margin-top: 24px;
            border-top: 1px solid #ccc;
        }
        .footer td      { padding-top: 10px; font-size: 8px; color: #777; }
        .footer .right  { text-align: right; }
    </style>
</head>
<body>

    {{-- Header --}}
    <table class="header">
        <tr>
            <td>
                <div class="brand">Whaspil Restaurant</div>
                <div class="brand-sub">Davao City · Point of Sale System</div>
            </td>
            <td class="right">
                <div class="rpt-title">Sales Report</div>
                <div class="rpt-meta">Generated: {{ now()->format('M d, Y h:i A') }}</div>
                <div class="rpt-meta">Generated by: {{ trim(($generatedBy->FNM ?? '') . ' ' . ($generatedBy->LNM ?? '')) ?: '—' }}</div>
            </td>
        </tr>
    </table>

    {{-- KPI Cards --}}
    <table class="kpi-row">
        <tr>
            <td class="kpi-card">
                <div class="kpi-label">Total Sales</div>
                <div class="kpi-value"><span class="peso">₱</span>{{ number_format($totalSales, 2) }}</div>
            </td>
            <td class="kpi-gap"></td>
            <td class="kpi-card">
                <div class="kpi-label">Transactions</div>
                <div class="kpi-value">{{ $orderCount }}</div>
            </td>
            <td class="kpi-gap"></td>
            <td class="kpi-card">
                <div class="kpi-label">Avg Ticket</div>
                <div class="kpi-value"><span class="peso">₱</span>{{ number_format($avgTicket, 2) }}</div>
            </td>
        </tr>
    </table>

    {{-- Transactions table --}}
    <table class="data">
        <thead>
            <tr>
                <th>Receipt #</th>
                <th>Table</th>
                <th>Date</th>
                <th>Time</th>
                <th>Cashier</th>
                <th>Method</th>
                <th class="th-amt">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($receipts as $r)
            <tr>
                <td class="tx-id">TX-{{ str_pad($r->Receipt_ID, 4, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $r->order->Table_number ?? '—' }}</td>
                <td>{{ \Carbon\Carbon::parse($r->Date)->format('M d, Y') }}</td>
                <td>{{ $r->created_at?->format('h:i A') }}</td>
                <td>{{ trim(($r->order->employee->FNM ?? '') . ' ' . ($r->order->employee->LNM ?? '')) ?: '—' }}</td>
                <td><span class="method-pill">{{ ucfirst($r->payment->Method ?? '—') }}</span></td>
                <td class="td-amt"><span class="peso">₱</span>{{ number_format($r->Total_Amount, 2) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align:center;padding:20px;color:#777">No transactions found.</td>
            </tr>
            @endforelse

            {{-- Total row --}}
            @if($receipts->isNotEmpty())
            <tr class="total-row">
                <td colspan="6">Total</td>
                <td class="td-amt"><span class="peso">₱</span>{{ number_format($totalSales, 2) }}</td>
            </tr>
            @endif
        </tbody>
    </table>

    {{-- Footer --}}
    <table class="footer">
        <tr>
            <td>Whaspil Restaurant POS · Confidential</td>
            <td class="right">{{ $orderCount }} transactions</td>
        </tr>
    </table>

</body>
</html>